### ISSUE TITLE
Allow access to branch name in variables

### ISSUE THREAD

**Issue by shyim** [itishermann/ollama-commit-summarizer#4]
My commit messages has to start with NEXT-1234 which can be extracted from branch name. For that I would like to have access to the branch name as variable

**Comment by itishermann** [comment]
I've added a new variable  `{{branchName}}` that will be available in the next release #5 
It was was sent for moderation today, it will be available on jetbrains marketplace in two business days max.
And if you have any other ideas, hmu with another issue

**Comment by shyim** [comment]
Thanks. btw getCurrentBranchName can give a null string back. than it will throw a exception. maybe return empty string instead of null :)
